Upload new external data package for every benchmark run

diff --git a/.github/workflows/android-device-test.yml b/.github/workflows/android-device-test.yml
--- a/.github/workflows/android-device-test.yml
+++ b/.github/workflows/android-device-test.yml
@@ -26,12 +26,6 @@ jobs:
             appFile: "MapboxGLAndroidSDKTestApp-drawable-release.apk",
             name: "Android Benchmark",
             testFilter: "org.maplibre.android.benchmark.Benchmark",
-            # echo '{"styleNames": [...], "styleURLs": [...], "resultsAPI: "..." }' > benchmark-input.json 
-            # zip benchmark-input.zip benchmark-input.json 
-            # aws devicefarm create-upload --project-arn <project_arn> --type EXTERNAL_DATA --name benchmark-input.zip
-            # curl -T benchmark-input.zip <upload_url>
-            # aws devicefarm get-upload <arn>
-            externalData: "arn:aws:devicefarm:us-west-2:373521797162:upload:20687d72-0e46-403e-8f03-0941850665bc/c27174c2-63f4-4cdb-9af9-68957d75ebed",
             # top devices, query with `aws list-device-pools --arn <project_arn>`
             devicePool: "arn:aws:devicefarm:us-west-2::devicepool:082d10e5-d7d7-48a5-ba5c-b33d66efa1f5",
             # benchmark-android.yaml
@@ -83,6 +77,33 @@ jobs:
         with:
           files: "${{ matrix.test.testFile }}, ${{ matrix.test.appFile }}"
 
+      - name: Upload external data for benchmark
+        if: matrix.test.name == 'Android Benchmark'
+        run: |
+          cat << EOF > benchmark-input.json
+          {
+            "styleNames": ["Facebook Light", "MapTiler Basic", "Americana"],
+            "styleURLs": [
+              "https://external.xx.fbcdn.net/maps/vt/style/canterbury_1_0/?locale=en_US",
+              "https://api.maptiler.com/maps/basic-v2/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL",
+              "https://zelonewolf.github.io/openstreetmap-americana/style.json"
+            ],
+            "resultsAPI": "${{ secrets.MLN_RESULTS_API }}"
+          }
+          EOF
+          zip benchmark-input.zip benchmark-input.json
+          upload_json="$(aws devicefarm create-upload --project-arn ${{ vars.AWS_DEVICE_FARM_PROJECT_ARN }} --type EXTERNAL_DATA --name benchmark-input.zip --output json)"
+          upload_url="$(echo "$upload_json" | jq -r '.upload.url')"
+          upload_arn="$(echo "$upload_json" | jq -r '.upload.arn')"
+          curl -T benchmark-input.zip "$upload_url"
+          upload_status="$(aws devicefarm get-upload --arn "$upload_arn" --output text --query upload.status)"
+          if [[ "$upload_status" != "SUCCEEDED" ]]; then
+            echo "Upload '$upload_arn' failed"
+            exit 1
+          fi
+
+          echo external_data_arn="$upload_arn" >> "$GITHUB_ENV"
+
       - uses: ./.github/actions/aws-device-farm-run
         if: steps.check_files.outputs.files_exists == 'true' && (matrix.test.name != 'Android Benchmark' || steps.fc.outputs.comment-id)
         with:
@@ -98,7 +119,7 @@ jobs:
           AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
           AWS_DEVICE_FARM_PROJECT_ARN: ${{ vars.AWS_DEVICE_FARM_PROJECT_ARN }}
           AWS_DEVICE_FARM_DEVICE_POOL_ARN: ${{ matrix.test.devicePool }}
-          externalData: ${{ matrix.test.externalData }}
+          externalData: ${{ env.external_data_arn }}
           testSpecArn: ${{ matrix.test.testSpecArn }}
 
       - uses: LouisBrunner/checks-action@v2.0.0
